### ISSUE TITLE
Bug report: smooth vanadium

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#182]
IPTS 22752 
RUN 171869

**Bug 1**

```
ith ID 18 is not recorded.
[DB...BAT] Removing Raw TOF: None
Traceback (most recent call last):
  File "/SNS/VULCAN/shared/PyVDrive/pyvdrive-in-develop/build/lib/pyvdrive/interface/PeakPickWindow.py", line 883, in evt_switch_bank
    self._subControllerVanadium.switch_bank(new_bank)
  File "/SNS/VULCAN/shared/PyVDrive/pyvdrive-in-develop/build/lib/pyvdrive/interface/PeakPickWindowVanadium.py", line 498, in switch_bank
    self.reset_image()
  File "/SNS/VULCAN/shared/PyVDrive/pyvdrive-in-develop/build/lib/pyvdrive/interface/PeakPickWindowVanadium.py", line 411, in reset_image
    self.show_hide_v_peaks(False)
  File "/SNS/VULCAN/shared/PyVDrive/pyvdrive-in-develop/build/lib/pyvdrive/interface/PeakPickWindowVanadium.py", line 104, in show_hide_v_peaks
    self.ui.graphicsView_main.remove_vanadium_peaks(self._vpeak_indicators)
  File "/SNS/VULCAN/shared/PyVDrive/pyvdrive-in-develop/build/lib/pyvdrive/interface/gui/diffractionplotview.py", line 1411, in remove_vanadium_peaks
    self.remove_indicator(peak_indicator)
  File "/SNS/VULCAN/shared/PyVDrive/pyvdrive-in-develop/build/lib/pyvdrive/interface/gui/mplgraphicsview.py", line 860, in remove_indicator
    ''.format(indicator_key, plot_id, run_err))
RuntimeError: Failed to remove indicator ID = 18 with plot ID = 18 due to Line with ID 18 is not recorded.
```

**Issue 2**

Why it takes a very long time to switch from _Peak Selection_ mode to _Vanadium processing_ mode.

**Comment by wdzhou** [comment]
**Suggested Solution**

1. a better manager of indicators (vanadium peaks positions)
2. writing tracing outputs for switching the mode
3. testing switching from vanadium peak processing mode to peak selection mode
