### ISSUE TITLE
Event filtering assistant UI shows manually generated splitters

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#190]
Event filtering assistant UI shall be able to show the splitters on the sample logs if the splitters are generated manually either by
 (1) manual selection
 (2) input files

Tasks
- [ ] 1. As a slicer file is loaded, the slicers shall be applied automatically
- [ ] 2. Add a current-slicer-tag label to UI
- [ ] 3. Try-catch the following
```
Traceback (most recent call last):
  File "/SNS/users/wzz/Projects/PyVDrive/PyVDrive/build/lib/pyvdrive/interface/LogPickerWindow.py", line 532, in do_show_manual_slicers
    self.evt_show_slicer()
  File "/SNS/users/wzz/Projects/PyVDrive/PyVDrive/build/lib/pyvdrive/interface/LogPickerWindow.py", line 1019, in evt_show_slicer
    status, ret_obj = self.get_controller().get_slicer(self._curr_run_number, self._currSlicerKey)
  File "/SNS/users/wzz/Projects/PyVDrive/PyVDrive/build/lib/pyvdrive/lib/VDriveAPI.py", line 560, in get_slicer
    status, ret_obj = chopper.get_slicer_by_id(slicer_tag=slicer_id, relative_time=True)
  File "/SNS/users/wzz/Projects/PyVDrive/PyVDrive/build/lib/pyvdrive/lib/chop_utility.py", line 319, in get_slicer_by_id
    '' % (str(slicer_tag), type(slicer_tag))
AssertionError: Slicer tag None must be a string but not a <type 'NoneType'>.
```

**Comment by wdzhou** [comment]
```
[DB...BAT] Set loadframe.furnace1 Y (1370.159579, 1371.698656) in color black as the figure's title.
ExportTimeSeriesLog-[Notice] ExportTimeSeriesLog started
ExportTimeSeriesLog-[Notice] ExportTimeSeriesLog successful, Duration 0.00 seconds
[DB...BAT] Set loadframe.strain Y (-0.000437, -0.000225) in color black as the figure's title.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 279, in mouseMoveEvent
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 1952, in motion_notify_event
    self.callbacks.process(s, event)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/home/wzz/Projects/PyVDrive/build/lib.linux-x86_64-2.7/pyvdrive/interface/gui/samplelogview.py", line 416, in on_mouse_motion
    self.select_picker(picker_id)
  File "/home/wzz/Projects/PyVDrive/build/lib.linux-x86_64-2.7/pyvdrive/interface/gui/samplelogview.py", line 441, in select_picker
    self.update_indicator(self._currentSelectedPicker, color='blue')
  File "/home/wzz/Projects/PyVDrive/build/lib.linux-x86_64-2.7/pyvdrive/interface/gui/mplgraphicsview.py", line 953, in update_indicator
    self._myCanvas.updateLine(ikey=canvas_line_index, vecx=None, vecy=y_range, linecolor=color)
  File "/home/wzz/Projects/PyVDrive/build/lib.linux-x86_64-2.7/pyvdrive/interface/gui/mplgraphicsview.py", line 1660, in updateLine
    ''.format(ikey, self._lineDict.keys()))
KeyError: 'Line ID 4 does not existing MPL existing keys: [7]'
```
