### ISSUE TITLE
Fix issues with reducing data

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#5]
Try to reduce data with auto vanadium run locator as acceptance test.  An exception is observed.  The error message is shown in the comment. 

Ke proposed a new GUI for PyVDrive.  The new UI files should be added here.

**Comment by wdzhou** [comment]
In order to facilitate the testing on different platform, the configuration file to set up reduction option from ~/.vdrive.config should be tested too.

**Comment by wdzhou** [comment]
Error message of reported issue:

CompressEvents-[Notice] CompressEvents started
CompressEvents-[Notice] CompressEvents successful, Duration 8.88 seconds
ConvertUnits-[Notice] ConvertUnits started
ConvertUnits-[Notice] ConvertUnits successful, Duration 0.00 seconds
SetSampleMaterial-[Notice] SetSampleMaterial started
SetSampleMaterial-[Notice] Found 1 types of atoms in "V"
SetSampleMaterial-[Notice] Sample number density = 0.0721 atoms/Angstrom^3
SetSampleMaterial-[Notice] Cross sections for wavelength = 1.7982 Angstroms
SetSampleMaterial-[Notice]     Coherent 0.0184 barns
SetSampleMaterial-[Notice]     Incoherent 5.08 barns
SetSampleMaterial-[Notice]     Total 5.1 barns
SetSampleMaterial-[Notice]     Absorption 5.08 barns
SetSampleMaterial-[Notice] PDF terms
SetSampleMaterial-[Notice]     <b>^2 = 0.14623
SetSampleMaterial-[Notice]     <b^2> = 0.14623
SetSampleMaterial-[Notice]     L     = 0
SetSampleMaterial-[Notice] Anvred LinearScatteringCoef = 0.36771 1/cm
SetSampleMaterial-[Notice] Anvred LinearAbsorptionCoef = 0.366268 1/cm
SetSampleMaterial-[Notice] SetSampleMaterial successful, Duration 0.00 seconds
MultipleScatteringCylinderAbsorption-[Notice] MultipleScatteringCylinderAbsorption started
MultipleScatteringCylinderAbsorption-[Notice] MultipleScatteringCylinderAbsorption successful, Duration 42.83 seconds
Traceback (most recent call last):
  File "/home/wzz/Projects/PyVDrive/PyVDrive/src/ui/Window_ReductionSetup.py", line 395, in evtReduceData
    self._myParent.getWorkflowObj().reduceData(projectname)
  File "/home/wzz/Projects/PyVDrive/PyVDrive/src/Ui_VDrive.py", line 653, in reduceData
    status, errmsg = project.reduceToPDData(normByVanadium=True)
  File "/home/wzz/Projects/PyVDrive/PyVDrive/src/vdrive/VDProject.py", line 416, in reduceToPDData
    vanws = vpdr.reduceVanadiumData(params={})
  File "/home/wzz/Projects/PyVDrive/PyVDrive/src/vdrive/SNSPowderReductionLite.py", line 207, in reduceVanadiumData
    wksp = self._doAlignFocus(wksp, params)
  File "/home/wzz/Projects/PyVDrive/PyVDrive/src/vdrive/SNSPowderReductionLite.py", line 434, in _doAlignFocus
    raise NotImplementedError("Input parameter must be of class AlignFocusParameters")
NotImplementedError: Input parameter must be of class AlignFocusParameters
