### ISSUE TITLE
Error report 03/07/2017

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#65]
From user's feedback (Chen Yan)
---------------------------------------------
View:
1. When showing "All" banks, can you use different colors for the patterns?
2. "Normalize by Vanadium" does not work. I used "runv=", it cannot show normalized pattern. 

Peak fit:
1. When I tried to create a peak list (by auto pick), all peaks were counted 5~6 times. (see the snapshot)
2. How can I set the peak name?

Solve 2 ploting errors: 
-----------------------------
Test data: any GSAS file

Bug 1:  

Suggstion: add more checking output

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 279, in mouseMoveEvent
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 1952, in motion_notify_event
    self.callbacks.process(s, event)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/home/wzz/Projects/PyVDrive/src/interface/gui/diffractionplotview.py", line 704, in on_mouse_motion
    self.highlight_peak_nearby(event.xdata)
  File "/home/wzz/Projects/PyVDrive/src/interface/gui/diffractionplotview.py", line 617, in highlight_peak_nearby
    self.update_indicator(peak_id, 'red')
  File "/home/wzz/Projects/PyVDrive/src/interface/gui/mplgraphicsview.py", line 740, in update_indicator
    if self._myIndicatorsManager.get_line_type(i_key) < 2:
  File "/home/wzz/Projects/PyVDrive/src/interface/gui/mplgraphicsview.py", line 178, in get_line_type
    return self._indicatorTypeDict[my_id]
KeyError: 0

Bug 2:

Suggestion: continue to add all methods

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 259, in mousePressEvent
    guiEvent=event)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 1903, in button_press_event
    self.callbacks.process(s, mouseevent)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/home/wzz/Projects/PyVDrive/src/interface/gui/diffractionplotview.py", line 984, in on_mouse_press_event
    self._pop_menu(event)
  File "/home/wzz/Projects/PyVDrive/src/interface/gui/diffractionplotview.py", line 1018, in _pop_menu
    if self._addedLeftBoundary:
AttributeError: 'DiffractionPlotView' object has no attribute '_addedLeftBoundary'

**Comment by wdzhou** [comment]
Bug 2: 3 menu options with group boundary are removed.
